fixed bunch of shit

diff --git a/VideoThumbnailerInstaller b/VideoThumbnailerInstaller
--- a/VideoThumbnailerInstaller
+++ b/VideoThumbnailerInstaller
@@ -1,33 +1,39 @@
 #!/bin/bash
-# written by staticsafe, ze, jayms and ckpro
+# written by staticsafe, ze, jayms, chris and ckpro
+# fixed various nasty things (thanks neurolysis)
 
-#installation
-cd $HOME
-mkdir bin
-echo "export PATH=$HOME/bin:$PATH" >> $HOME/.bashrc
-arch="$(uname -m)"
-case "$arch" in
-  i686|i586) wget -O mtn http://dl.dropbox.com/u/34659045/mtn-32 ;;
-  x86_64) wget -O mtn http://dl.dropbox.com/u/34659045/mtn-64 ;;
-  *) printf "Unknown arch \"$arch\", aborting.\n">/dev/stderr ; exit 1 ;;
+arch=$(uname -m)
+
+die() {
+	printf '%s\n' "$@" >&2
+	exit 1
+}
+
+# Installation
+if [[ ! -d ~/bin ]]; then
+	mkdir ~/bin || die 'Failed to create ~/bin.'
+fi
+
+printf '%s\n' 'PATH="$HOME/bin:$PATH"' >> ~/.bashrc
+case "${arch}" in
+	i686|i586) wget -O ~/bin/mtn http://dl.dropbox.com/u/34659045/mtn-32 || die 'Failed to download mtn.' ;;
+	x86_64) wget -O ~/bin/mtn http://dl.dropbox.com/u/34659045/mtn-64 || die 'Failed to download mtn.' ;;
+	*) die "Unknown arch '${arch}', aborting." ;;
 esac
-chmod +x mtn
-mv mtn $HOME/bin
+chmod a+x ~/bin/mtn
 
 # Get font
-cd $HOME
-wget http://fractal.csie.org/~eric/Terminus.ttf # Downloads font file
+wget -O ~/bin/ http://fractal.csie.org/~eric/Terminus.ttf
 
 # Create mkscr bash script
-cat >mkscr <<EOF
+cat > ~/bin/mkscr << 'EOF'
 #!/bin/bash
-while [ $# -gt 0 ]; do
-  mtn -f ~/Terminus.ttf -c 4 -r 8 -w 1280 -b 0.6 -D6 -T "Screens for site" "$1"
-  shift
+for arg; do
+	mtn -f ~/bin/Terminus.ttf -c 4 -r 8 -w 1280 -b 0.6 -D6 -T "Screens for hey.fux0r.eu" "${arg}"
 done
 EOF
 
-chmod +x mkscr
-mv mkscr $HOME/bin
+chmod a+x ~/bin/mkscr
 
-printf "\033[31m Done. Happy screenshotting! \033[0m\n"
+printf '%s\n' 'Done. Happy screenshotting!'
+
